default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: root
  password: usrio01

development:
  <<: *default
  database: jes_development

test:
  <<: *default
  database: jes_test

production:
  <<: *default
  database: jes_production
  username: jes
  password: <%= ENV['JES_DATABASE_PASSWORD'] %>
